import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";

import { APP_NAME } from "@/lib/constants";
import { cn } from "@/lib/utils";

import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: `${APP_NAME} | Next.js`,
    template: `%s | ${APP_NAME}`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(interSans.variable, "antialiased min-h-screen")}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
